// Code generated by cmd/codegen. DO NOT EDIT.

package lamvms

import (
	"bytes"
	"encoding/json"
	"fmt"

	"github.com/aws/aws-sdk-go-v2/service/lambdamicrovms"
	"github.com/aws/aws-sdk-go-v2/service/lambdamicrovms/types"
)

// MicrovmImage represents configuration based on CreateMicrovmImageInput.
type MicrovmImage lambdamicrovms.CreateMicrovmImageInput

// UnmarshalJSON implements custom unmarshaling for MicrovmImage.
func (m *MicrovmImage) UnmarshalJSON(data []byte) error {
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}

	rawCodeArtifact := raw["CodeArtifact"]
	delete(raw, "CodeArtifact")
	rawLogging := raw["Logging"]
	delete(raw, "Logging")

	cleaned, err := json.Marshal(raw)
	if err != nil {
		return err
	}

	type plain lambdamicrovms.CreateMicrovmImageInput
	var p plain
	if err := json.Unmarshal(cleaned, &p); err != nil {
		return err
	}
	*m = MicrovmImage(p)

	if len(rawCodeArtifact) > 0 && string(rawCodeArtifact) != "null" {
		var obj any
		if err := json.Unmarshal(rawCodeArtifact, &obj); err != nil {
			return fmt.Errorf("CodeArtifact: %w", err)
		}
		v, err := convertToCodeArtifact(obj)
		if err != nil {
			return fmt.Errorf("CodeArtifact: %w", err)
		}
		m.CodeArtifact = v
	}
	if len(rawLogging) > 0 && string(rawLogging) != "null" {
		var obj any
		if err := json.Unmarshal(rawLogging, &obj); err != nil {
			return fmt.Errorf("Logging: %w", err)
		}
		v, err := convertToLogging(obj)
		if err != nil {
			return fmt.Errorf("Logging: %w", err)
		}
		m.Logging = v
	}

	return nil
}

// MarshalJSON implements custom marshaling for MicrovmImage.
func (m MicrovmImage) MarshalJSON() ([]byte, error) {
	type plain lambdamicrovms.CreateMicrovmImageInput
	p := plain(m)

	p.CodeArtifact = nil
	p.Logging = nil

	data, err := json.Marshal(p)
	if err != nil {
		return nil, err
	}

	var obj map[string]any
	if err := json.Unmarshal(data, &obj); err != nil {
		return nil, err
	}

	if m.CodeArtifact != nil {
		v, err := convertFromCodeArtifact(m.CodeArtifact)
		if err != nil {
			return nil, fmt.Errorf("CodeArtifact: %w", err)
		}
		obj["CodeArtifact"] = v
	}
	if m.Logging != nil {
		v, err := convertFromLogging(m.Logging)
		if err != nil {
			return nil, fmt.Errorf("Logging: %w", err)
		}
		obj["Logging"] = v
	}

	return json.Marshal(omitEmptyValues(obj))
}

// RunConfig represents configuration based on RunMicrovmInput.
type RunConfig lambdamicrovms.RunMicrovmInput

// UnmarshalJSON implements custom unmarshaling for RunConfig.
func (m *RunConfig) UnmarshalJSON(data []byte) error {
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}

	rawLogging := raw["Logging"]
	delete(raw, "Logging")

	cleaned, err := json.Marshal(raw)
	if err != nil {
		return err
	}

	type plain lambdamicrovms.RunMicrovmInput
	var p plain
	if err := json.Unmarshal(cleaned, &p); err != nil {
		return err
	}
	*m = RunConfig(p)

	if len(rawLogging) > 0 && string(rawLogging) != "null" {
		var obj any
		if err := json.Unmarshal(rawLogging, &obj); err != nil {
			return fmt.Errorf("Logging: %w", err)
		}
		v, err := convertToLogging(obj)
		if err != nil {
			return fmt.Errorf("Logging: %w", err)
		}
		m.Logging = v
	}

	return nil
}

// MarshalJSON implements custom marshaling for RunConfig.
func (m RunConfig) MarshalJSON() ([]byte, error) {
	type plain lambdamicrovms.RunMicrovmInput
	p := plain(m)

	p.Logging = nil

	data, err := json.Marshal(p)
	if err != nil {
		return nil, err
	}

	var obj map[string]any
	if err := json.Unmarshal(data, &obj); err != nil {
		return nil, err
	}

	if m.Logging != nil {
		v, err := convertFromLogging(m.Logging)
		if err != nil {
			return nil, fmt.Errorf("Logging: %w", err)
		}
		obj["Logging"] = v
	}

	return json.Marshal(omitEmptyValues(obj))
}

func newUpdateMicrovmImageInput(img *MicrovmImage, imageIdentifier string) *lambdamicrovms.UpdateMicrovmImageInput {
	return &lambdamicrovms.UpdateMicrovmImageInput{
		ImageIdentifier:          &imageIdentifier,
		BaseImageArn:             img.BaseImageArn,
		BuildRoleArn:             img.BuildRoleArn,
		CodeArtifact:             img.CodeArtifact,
		AdditionalOsCapabilities: img.AdditionalOsCapabilities,
		BaseImageVersion:         img.BaseImageVersion,
		CpuConfigurations:        img.CpuConfigurations,
		Description:              img.Description,
		EgressNetworkConnectors:  img.EgressNetworkConnectors,
		EnvironmentVariables:     img.EnvironmentVariables,
		Hooks:                    img.Hooks,
		Logging:                  img.Logging,
		Resources:                img.Resources,
	}
}

func convertToCodeArtifact(v any) (types.CodeArtifact, error) {
	data, err := json.Marshal(v)
	if err != nil {
		return nil, err
	}
	var variants struct {
		Uri *string `json:"uri"`
	}
	dec := json.NewDecoder(bytes.NewReader(data))
	if err := dec.Decode(&variants); err != nil {
		return nil, err
	}

	if variants.Uri != nil {
		return &types.CodeArtifactMemberUri{
			Value: *variants.Uri,
		}, nil
	}

	return nil, fmt.Errorf("no valid variant found for CodeArtifact")
}

func convertFromCodeArtifact(v types.CodeArtifact) (any, error) {
	if v == nil {
		return nil, nil
	}
	switch v := v.(type) {
	case *types.CodeArtifactMemberUri:
		return map[string]any{
			"uri": v.Value,
		}, nil
	default:
		return nil, fmt.Errorf("unknown CodeArtifact type: %T", v)
	}
}

func convertToLogging(v any) (types.Logging, error) {
	data, err := json.Marshal(v)
	if err != nil {
		return nil, err
	}
	var variants struct {
		CloudWatch *types.CloudWatchLogging `json:"cloudWatch"`
		Disabled   *types.LoggingDisabled   `json:"disabled"`
	}
	dec := json.NewDecoder(bytes.NewReader(data))
	if err := dec.Decode(&variants); err != nil {
		return nil, err
	}

	if variants.CloudWatch != nil {
		return &types.LoggingMemberCloudWatch{
			Value: *variants.CloudWatch,
		}, nil
	}

	if variants.Disabled != nil {
		return &types.LoggingMemberDisabled{
			Value: *variants.Disabled,
		}, nil
	}

	return nil, fmt.Errorf("no valid variant found for Logging")
}

func convertFromLogging(v types.Logging) (any, error) {
	if v == nil {
		return nil, nil
	}
	switch v := v.(type) {
	case *types.LoggingMemberCloudWatch:
		return map[string]any{
			"cloudWatch": v.Value,
		}, nil
	case *types.LoggingMemberDisabled:
		return map[string]any{
			"disabled": v.Value,
		}, nil
	default:
		return nil, fmt.Errorf("unknown Logging type: %T", v)
	}
}
