// Code generated by MockGen. DO NOT EDIT.
// Source: lamvms.go
//
// Generated by this command:
//
//	mockgen -source=lamvms.go -destination=mock_test.go -package=lamvms
//

// Package lamvms is a generated GoMock package.
package lamvms

import (
	context "context"
	reflect "reflect"

	lambdamicrovms "github.com/aws/aws-sdk-go-v2/service/lambdamicrovms"
	gomock "go.uber.org/mock/gomock"
)

// MockLambdaMicroVMsClient is a mock of LambdaMicroVMsClient interface.
type MockLambdaMicroVMsClient struct {
	ctrl     *gomock.Controller
	recorder *MockLambdaMicroVMsClientMockRecorder
	isgomock struct{}
}

// MockLambdaMicroVMsClientMockRecorder is the mock recorder for MockLambdaMicroVMsClient.
type MockLambdaMicroVMsClientMockRecorder struct {
	mock *MockLambdaMicroVMsClient
}

// NewMockLambdaMicroVMsClient creates a new mock instance.
func NewMockLambdaMicroVMsClient(ctrl *gomock.Controller) *MockLambdaMicroVMsClient {
	mock := &MockLambdaMicroVMsClient{ctrl: ctrl}
	mock.recorder = &MockLambdaMicroVMsClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLambdaMicroVMsClient) EXPECT() *MockLambdaMicroVMsClientMockRecorder {
	return m.recorder
}

// CreateMicrovmAuthToken mocks base method.
func (m *MockLambdaMicroVMsClient) CreateMicrovmAuthToken(ctx context.Context, params *lambdamicrovms.CreateMicrovmAuthTokenInput, optFns ...func(*lambdamicrovms.Options)) (*lambdamicrovms.CreateMicrovmAuthTokenOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateMicrovmAuthToken", varargs...)
	ret0, _ := ret[0].(*lambdamicrovms.CreateMicrovmAuthTokenOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateMicrovmAuthToken indicates an expected call of CreateMicrovmAuthToken.
func (mr *MockLambdaMicroVMsClientMockRecorder) CreateMicrovmAuthToken(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMicrovmAuthToken", reflect.TypeOf((*MockLambdaMicroVMsClient)(nil).CreateMicrovmAuthToken), varargs...)
}

// CreateMicrovmImage mocks base method.
func (m *MockLambdaMicroVMsClient) CreateMicrovmImage(ctx context.Context, params *lambdamicrovms.CreateMicrovmImageInput, optFns ...func(*lambdamicrovms.Options)) (*lambdamicrovms.CreateMicrovmImageOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateMicrovmImage", varargs...)
	ret0, _ := ret[0].(*lambdamicrovms.CreateMicrovmImageOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateMicrovmImage indicates an expected call of CreateMicrovmImage.
func (mr *MockLambdaMicroVMsClientMockRecorder) CreateMicrovmImage(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMicrovmImage", reflect.TypeOf((*MockLambdaMicroVMsClient)(nil).CreateMicrovmImage), varargs...)
}

// CreateMicrovmShellAuthToken mocks base method.
func (m *MockLambdaMicroVMsClient) CreateMicrovmShellAuthToken(ctx context.Context, params *lambdamicrovms.CreateMicrovmShellAuthTokenInput, optFns ...func(*lambdamicrovms.Options)) (*lambdamicrovms.CreateMicrovmShellAuthTokenOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateMicrovmShellAuthToken", varargs...)
	ret0, _ := ret[0].(*lambdamicrovms.CreateMicrovmShellAuthTokenOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateMicrovmShellAuthToken indicates an expected call of CreateMicrovmShellAuthToken.
func (mr *MockLambdaMicroVMsClientMockRecorder) CreateMicrovmShellAuthToken(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMicrovmShellAuthToken", reflect.TypeOf((*MockLambdaMicroVMsClient)(nil).CreateMicrovmShellAuthToken), varargs...)
}

// DeleteMicrovmImage mocks base method.
func (m *MockLambdaMicroVMsClient) DeleteMicrovmImage(ctx context.Context, params *lambdamicrovms.DeleteMicrovmImageInput, optFns ...func(*lambdamicrovms.Options)) (*lambdamicrovms.DeleteMicrovmImageOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteMicrovmImage", varargs...)
	ret0, _ := ret[0].(*lambdamicrovms.DeleteMicrovmImageOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteMicrovmImage indicates an expected call of DeleteMicrovmImage.
func (mr *MockLambdaMicroVMsClientMockRecorder) DeleteMicrovmImage(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMicrovmImage", reflect.TypeOf((*MockLambdaMicroVMsClient)(nil).DeleteMicrovmImage), varargs...)
}

// DeleteMicrovmImageVersion mocks base method.
func (m *MockLambdaMicroVMsClient) DeleteMicrovmImageVersion(ctx context.Context, params *lambdamicrovms.DeleteMicrovmImageVersionInput, optFns ...func(*lambdamicrovms.Options)) (*lambdamicrovms.DeleteMicrovmImageVersionOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteMicrovmImageVersion", varargs...)
	ret0, _ := ret[0].(*lambdamicrovms.DeleteMicrovmImageVersionOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteMicrovmImageVersion indicates an expected call of DeleteMicrovmImageVersion.
func (mr *MockLambdaMicroVMsClientMockRecorder) DeleteMicrovmImageVersion(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMicrovmImageVersion", reflect.TypeOf((*MockLambdaMicroVMsClient)(nil).DeleteMicrovmImageVersion), varargs...)
}

// GetMicrovm mocks base method.
func (m *MockLambdaMicroVMsClient) GetMicrovm(ctx context.Context, params *lambdamicrovms.GetMicrovmInput, optFns ...func(*lambdamicrovms.Options)) (*lambdamicrovms.GetMicrovmOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetMicrovm", varargs...)
	ret0, _ := ret[0].(*lambdamicrovms.GetMicrovmOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMicrovm indicates an expected call of GetMicrovm.
func (mr *MockLambdaMicroVMsClientMockRecorder) GetMicrovm(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMicrovm", reflect.TypeOf((*MockLambdaMicroVMsClient)(nil).GetMicrovm), varargs...)
}

// GetMicrovmImage mocks base method.
func (m *MockLambdaMicroVMsClient) GetMicrovmImage(ctx context.Context, params *lambdamicrovms.GetMicrovmImageInput, optFns ...func(*lambdamicrovms.Options)) (*lambdamicrovms.GetMicrovmImageOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetMicrovmImage", varargs...)
	ret0, _ := ret[0].(*lambdamicrovms.GetMicrovmImageOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMicrovmImage indicates an expected call of GetMicrovmImage.
func (mr *MockLambdaMicroVMsClientMockRecorder) GetMicrovmImage(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMicrovmImage", reflect.TypeOf((*MockLambdaMicroVMsClient)(nil).GetMicrovmImage), varargs...)
}

// GetMicrovmImageVersion mocks base method.
func (m *MockLambdaMicroVMsClient) GetMicrovmImageVersion(ctx context.Context, params *lambdamicrovms.GetMicrovmImageVersionInput, optFns ...func(*lambdamicrovms.Options)) (*lambdamicrovms.GetMicrovmImageVersionOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetMicrovmImageVersion", varargs...)
	ret0, _ := ret[0].(*lambdamicrovms.GetMicrovmImageVersionOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMicrovmImageVersion indicates an expected call of GetMicrovmImageVersion.
func (mr *MockLambdaMicroVMsClientMockRecorder) GetMicrovmImageVersion(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMicrovmImageVersion", reflect.TypeOf((*MockLambdaMicroVMsClient)(nil).GetMicrovmImageVersion), varargs...)
}

// ListMicrovmImageBuilds mocks base method.
func (m *MockLambdaMicroVMsClient) ListMicrovmImageBuilds(ctx context.Context, params *lambdamicrovms.ListMicrovmImageBuildsInput, optFns ...func(*lambdamicrovms.Options)) (*lambdamicrovms.ListMicrovmImageBuildsOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListMicrovmImageBuilds", varargs...)
	ret0, _ := ret[0].(*lambdamicrovms.ListMicrovmImageBuildsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMicrovmImageBuilds indicates an expected call of ListMicrovmImageBuilds.
func (mr *MockLambdaMicroVMsClientMockRecorder) ListMicrovmImageBuilds(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMicrovmImageBuilds", reflect.TypeOf((*MockLambdaMicroVMsClient)(nil).ListMicrovmImageBuilds), varargs...)
}

// ListMicrovmImageVersions mocks base method.
func (m *MockLambdaMicroVMsClient) ListMicrovmImageVersions(ctx context.Context, params *lambdamicrovms.ListMicrovmImageVersionsInput, optFns ...func(*lambdamicrovms.Options)) (*lambdamicrovms.ListMicrovmImageVersionsOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListMicrovmImageVersions", varargs...)
	ret0, _ := ret[0].(*lambdamicrovms.ListMicrovmImageVersionsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMicrovmImageVersions indicates an expected call of ListMicrovmImageVersions.
func (mr *MockLambdaMicroVMsClientMockRecorder) ListMicrovmImageVersions(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMicrovmImageVersions", reflect.TypeOf((*MockLambdaMicroVMsClient)(nil).ListMicrovmImageVersions), varargs...)
}

// ListMicrovmImages mocks base method.
func (m *MockLambdaMicroVMsClient) ListMicrovmImages(ctx context.Context, params *lambdamicrovms.ListMicrovmImagesInput, optFns ...func(*lambdamicrovms.Options)) (*lambdamicrovms.ListMicrovmImagesOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListMicrovmImages", varargs...)
	ret0, _ := ret[0].(*lambdamicrovms.ListMicrovmImagesOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMicrovmImages indicates an expected call of ListMicrovmImages.
func (mr *MockLambdaMicroVMsClientMockRecorder) ListMicrovmImages(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMicrovmImages", reflect.TypeOf((*MockLambdaMicroVMsClient)(nil).ListMicrovmImages), varargs...)
}

// ListMicrovms mocks base method.
func (m *MockLambdaMicroVMsClient) ListMicrovms(ctx context.Context, params *lambdamicrovms.ListMicrovmsInput, optFns ...func(*lambdamicrovms.Options)) (*lambdamicrovms.ListMicrovmsOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListMicrovms", varargs...)
	ret0, _ := ret[0].(*lambdamicrovms.ListMicrovmsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMicrovms indicates an expected call of ListMicrovms.
func (mr *MockLambdaMicroVMsClientMockRecorder) ListMicrovms(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMicrovms", reflect.TypeOf((*MockLambdaMicroVMsClient)(nil).ListMicrovms), varargs...)
}

// ListTags mocks base method.
func (m *MockLambdaMicroVMsClient) ListTags(ctx context.Context, params *lambdamicrovms.ListTagsInput, optFns ...func(*lambdamicrovms.Options)) (*lambdamicrovms.ListTagsOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListTags", varargs...)
	ret0, _ := ret[0].(*lambdamicrovms.ListTagsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTags indicates an expected call of ListTags.
func (mr *MockLambdaMicroVMsClientMockRecorder) ListTags(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTags", reflect.TypeOf((*MockLambdaMicroVMsClient)(nil).ListTags), varargs...)
}

// ResumeMicrovm mocks base method.
func (m *MockLambdaMicroVMsClient) ResumeMicrovm(ctx context.Context, params *lambdamicrovms.ResumeMicrovmInput, optFns ...func(*lambdamicrovms.Options)) (*lambdamicrovms.ResumeMicrovmOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ResumeMicrovm", varargs...)
	ret0, _ := ret[0].(*lambdamicrovms.ResumeMicrovmOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResumeMicrovm indicates an expected call of ResumeMicrovm.
func (mr *MockLambdaMicroVMsClientMockRecorder) ResumeMicrovm(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResumeMicrovm", reflect.TypeOf((*MockLambdaMicroVMsClient)(nil).ResumeMicrovm), varargs...)
}

// RunMicrovm mocks base method.
func (m *MockLambdaMicroVMsClient) RunMicrovm(ctx context.Context, params *lambdamicrovms.RunMicrovmInput, optFns ...func(*lambdamicrovms.Options)) (*lambdamicrovms.RunMicrovmOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RunMicrovm", varargs...)
	ret0, _ := ret[0].(*lambdamicrovms.RunMicrovmOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RunMicrovm indicates an expected call of RunMicrovm.
func (mr *MockLambdaMicroVMsClientMockRecorder) RunMicrovm(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunMicrovm", reflect.TypeOf((*MockLambdaMicroVMsClient)(nil).RunMicrovm), varargs...)
}

// SuspendMicrovm mocks base method.
func (m *MockLambdaMicroVMsClient) SuspendMicrovm(ctx context.Context, params *lambdamicrovms.SuspendMicrovmInput, optFns ...func(*lambdamicrovms.Options)) (*lambdamicrovms.SuspendMicrovmOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SuspendMicrovm", varargs...)
	ret0, _ := ret[0].(*lambdamicrovms.SuspendMicrovmOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SuspendMicrovm indicates an expected call of SuspendMicrovm.
func (mr *MockLambdaMicroVMsClientMockRecorder) SuspendMicrovm(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SuspendMicrovm", reflect.TypeOf((*MockLambdaMicroVMsClient)(nil).SuspendMicrovm), varargs...)
}

// TagResource mocks base method.
func (m *MockLambdaMicroVMsClient) TagResource(ctx context.Context, params *lambdamicrovms.TagResourceInput, optFns ...func(*lambdamicrovms.Options)) (*lambdamicrovms.TagResourceOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "TagResource", varargs...)
	ret0, _ := ret[0].(*lambdamicrovms.TagResourceOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TagResource indicates an expected call of TagResource.
func (mr *MockLambdaMicroVMsClientMockRecorder) TagResource(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TagResource", reflect.TypeOf((*MockLambdaMicroVMsClient)(nil).TagResource), varargs...)
}

// TerminateMicrovm mocks base method.
func (m *MockLambdaMicroVMsClient) TerminateMicrovm(ctx context.Context, params *lambdamicrovms.TerminateMicrovmInput, optFns ...func(*lambdamicrovms.Options)) (*lambdamicrovms.TerminateMicrovmOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "TerminateMicrovm", varargs...)
	ret0, _ := ret[0].(*lambdamicrovms.TerminateMicrovmOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TerminateMicrovm indicates an expected call of TerminateMicrovm.
func (mr *MockLambdaMicroVMsClientMockRecorder) TerminateMicrovm(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TerminateMicrovm", reflect.TypeOf((*MockLambdaMicroVMsClient)(nil).TerminateMicrovm), varargs...)
}

// UntagResource mocks base method.
func (m *MockLambdaMicroVMsClient) UntagResource(ctx context.Context, params *lambdamicrovms.UntagResourceInput, optFns ...func(*lambdamicrovms.Options)) (*lambdamicrovms.UntagResourceOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UntagResource", varargs...)
	ret0, _ := ret[0].(*lambdamicrovms.UntagResourceOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UntagResource indicates an expected call of UntagResource.
func (mr *MockLambdaMicroVMsClientMockRecorder) UntagResource(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UntagResource", reflect.TypeOf((*MockLambdaMicroVMsClient)(nil).UntagResource), varargs...)
}

// UpdateMicrovmImage mocks base method.
func (m *MockLambdaMicroVMsClient) UpdateMicrovmImage(ctx context.Context, params *lambdamicrovms.UpdateMicrovmImageInput, optFns ...func(*lambdamicrovms.Options)) (*lambdamicrovms.UpdateMicrovmImageOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateMicrovmImage", varargs...)
	ret0, _ := ret[0].(*lambdamicrovms.UpdateMicrovmImageOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateMicrovmImage indicates an expected call of UpdateMicrovmImage.
func (mr *MockLambdaMicroVMsClientMockRecorder) UpdateMicrovmImage(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMicrovmImage", reflect.TypeOf((*MockLambdaMicroVMsClient)(nil).UpdateMicrovmImage), varargs...)
}

// UpdateMicrovmImageVersion mocks base method.
func (m *MockLambdaMicroVMsClient) UpdateMicrovmImageVersion(ctx context.Context, params *lambdamicrovms.UpdateMicrovmImageVersionInput, optFns ...func(*lambdamicrovms.Options)) (*lambdamicrovms.UpdateMicrovmImageVersionOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateMicrovmImageVersion", varargs...)
	ret0, _ := ret[0].(*lambdamicrovms.UpdateMicrovmImageVersionOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateMicrovmImageVersion indicates an expected call of UpdateMicrovmImageVersion.
func (mr *MockLambdaMicroVMsClientMockRecorder) UpdateMicrovmImageVersion(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMicrovmImageVersion", reflect.TypeOf((*MockLambdaMicroVMsClient)(nil).UpdateMicrovmImageVersion), varargs...)
}
